### ISSUE TITLE
Connect Timeout Error

### ISSUE THREAD

**Issue by miuzkle** [mark-magic/mark-magic#7]
my web-clipper is running ok,and the fallware is closed,but it's does't work,is anything configure error?

```shell
miuzkle@debian-nas:~/project/hexo_blog$ npx mark-magic
  Error in task: blog
[18:19:06.874] ERROR (114834): fetch failed
    err: {
      "type": "TypeError",
      "message": "fetch failed: Connect Timeout Error",
      "stack":
          TypeError: fetch failed
              at node:internal/deps/undici/undici:12345:11
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async Ajax.request (file:///home/miuzkle/project/hexo_blog/node_modules/joplin-api/dist/index.js:400:18)
              at async E (file:///home/miuzkle/project/hexo_blog/node_modules/@mark-magic/plugin-joplin/dist/index.js:11:13)
              at async Object.generate (file:///home/miuzkle/project/hexo_blog/node_modules/@mark-magic/plugin-joplin/dist/index.js:43:17)
              at async file:///home/miuzkle/project/hexo_blog/node_modules/@mark-magic/core/dist/index.js:21:20
              at async j (file:///home/miuzkle/project/hexo_blog/node_modules/@mark-magic/cli/dist/bin.js:106:7)
              at async Command.<anonymous> (file:///home/miuzkle/project/hexo_blog/node_modules/@mark-magic/cli/dist/bin.js:120:3)
          caused by: ConnectTimeoutError: Connect Timeout Error
              at onConnectTimeout (node:internal/deps/undici/undici:7492:28)
              at node:internal/deps/undici/undici:7448:50
              at Immediate._onImmediate (node:internal/deps/undici/undici:7480:13)
              at process.processImmediate (node:internal/timers:478:21)
    }
```

config
![image](https://github.com/mark-magic/mark-magic/assets/163179470/24e22e24-0896-4544-be64-6c186211aadc)
![image](https://github.com/mark-magic/mark-magic/assets/163179470/9bbff326-7f02-4c3d-94e4-cbc7395dc58b)
![image](https://github.com/mark-magic/mark-magic/assets/163179470/8a3a2404-d25c-4a71-8005-af198dba8d9b)
![image](https://github.com/mark-magic/mark-magic/assets/163179470/1cf1c1ab-9187-4905-bede-e81ff3a8c4a8)

**Comment by rxliuli** [comment]
Try updating all dependencies of @mark-magic/* to the latest versions. If there are errors, they are likely to be the following two.

1. **Failed to connect to Joplin**: This is generally because the Joplin service has not started correctly. Use `<baseUrl>/ping` to verify, for example, `http://localhost:41184/ping`
2. **The token is invalid**: This is generally because the token is incorrect. Use `<baseUrl>/notes?token=<token>` to verify.

**Comment by miuzkle** [comment]
Thank you for reminding me.

Tested that the local host (windows) cannot access the local host through `http://10.168.1.9:41184/ping`, even if the forwarding is set up, so the devices under the same local area network are the same. It is estimated that there are relevant restrictions within the joplin.
